Moved loadPrices-function to tokenStorage independent class
bestit/symfony-commercetools-customer-prices-bundle pull request #8
Opened 2018-01-30 08:23 UTC by avareldev

I need to use the collection and loadPrices function independent from the current user, but by passing in a CustomerInteface-object.

2018-01-30 09:08 UTC, migo315 requested changes
Grundsätzlich OK. Fände es aber weitaus sauberer, wenn die ByUserFactory die neue CustomerPriceCollectionFactory injected und nicht extended. Kannst du die Kleinigkeit noch ändern?

2018-01-30 09:29 UTC, migo315 approved these changes
Sieht für mich gut aus

2018-01-30 09:59 UTC, nhardeweg requested changes

2018-01-30 09:59 UTC, nhardeweg commented on src/Model/CustomerPriceCollection/CustomerPriceCollectionFactory.php
> +     * @param QueryHelper $queryHelper
QueryHelper|null

2018-01-30 10:09 UTC, avareldev commented
All errors resolved

2018-01-30 10:17 UTC, nhardeweg approved these changes

2018-01-30 10:17 UTC, merged

2018-01-31 06:53 UTC, b3nl commented
@migo315 Factory in Factory? Habe ich dann mal umgestellt.

2018-01-31 08:02 UTC, migo315 commented
Habe ich gestern Abend schon gesehen ;-P

Factory ist ja nur eine Benennung. Imho wäre die CustomerPriceCollectionFactory eh eher ein "Loader", "Fetcher", "Repository" o.ä. - Und dann würde dies auch wieder passen, wenn die Factory das "Repository" injected und nutzt.